on: [push, pull_request]

name: Test

jobs:
  code-quality:
    name: Code Quality
    runs-on: ubuntu-latest

    steps:
      - name: Copy files from repo
        uses: actions/checkout@v5
      
      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry config virtualenvs.create false
      
      - name: Install dependencies
        run: poetry install
      
      - name: Run Ruff
        run: poetry run ruff check .; poetry run ruff check . --diff
    
      - name: Run Radon
        run: poetry run radon cc ./confy_addons -a -na
    
      - name: Run Bandit
        run: poetry run bandit -r ./confy_addons
  
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12', '3.13']
    steps:
      - name: Copy files from repo
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry config virtualenvs.create false

      - name: Install dependencies
        run: poetry install

      - name: Run Tests
        run: poetry run pytest -s -x --cov=confy_addons -vv
  
  test-with-coverage:
    name: Run Tests on Python 3.14
    runs-on: ubuntu-latest
    steps:
      - name: Copy files from repo
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry config virtualenvs.create false

      - name: Install dependencies
        run: poetry install

      - name: Run Tests
        run: poetry run task test
          
      - name: Store coverage files
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: htmlcov